# Generated by Django 4.2.17 on 2025-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmovement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
