# Generated by Django 4.2.16 on 2025-01-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_stock',
        ),
    ]
