# Generated by Django 4.2.17 on 2025-01-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_contact_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_person',
            new_name='contact',
        ),
    ]
