# Generated by Django 4.2.17 on 2025-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_saleitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
